# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  wajebapi:
    image: wajebapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5001:5001
